sonar.projectKey=S-GOST_FRONTEND
sonar.projectName=FRONTEND
sonar.organization=s-gost
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests/Pruebas unitarias
sonar.test.inclusions=tests/Pruebas unitarias/**/*.{test,spec}.{js,ts,jsx,tsx}
sonar.javascript.lcov.reportPaths=coverage/lcov.info
