import { Service, SearchSuggestion } from '../types';

export const servicesData: Service[] = [
  // Mantenimiento
  {
    id: 'mantenimiento_preventivo',
    name: 'Mantenimiento Preventivo',
    category: 'Mantenimiento',
    price: 120.00,
    description: 'Inspecciones programadas y mantenimiento regular para prevenir fallos y optimizar el rendimiento de tu motocicleta.',
    icon: 'bi-shield-check',
  },
  {
    id: 'mantenimiento_correctivo',
    name: 'Mantenimiento Correctivo',
    category: 'Mantenimiento',
    price: 200.00,
    description: 'Reparación de fallas y averías existentes para restaurar la funcionalidad completa de tu motocicleta.',
    icon: 'bi-wrench-adjustable',
  },
  {
    id: 'mantenimiento_predictivo',
    name: 'Mantenimiento Predictivo',
    category: 'Mantenimiento',
    price: 180.00,
    description: 'Monitoreo y análisis avanzado para anticipar fallas y programar intervenciones antes de que ocurran problemas.',
    icon: 'bi-graph-up-arrow',
  },
  {
    id: 'mantenimiento_proactivo',
    name: 'Mantenimiento Proactivo',
    category: 'Mantenimiento',
    price: 250.00,
    description: 'Mejoras continuas y optimización del rendimiento para maximizar la vida útil y el desempeño de tu motocicleta.',
    icon: 'bi-lightning-charge',
  },
  // Reparaciones
  {
    id: 'reparaciones_danios',
    name: 'Reparaciones por Daños',
    category: 'Reparaciones',
    price: 350.00,
    description: 'Reparación integral de daños estructurales y funcionales causados por accidentes o uso intensivo.',
    icon: 'bi-tools',
  },
  {
    id: 'motorizacion_transmision',
    name: 'Motorización y Transmisión',
    category: 'Reparaciones',
    price: 500.00,
    description: 'Reparación y ajuste de motores, cajas de cambios, embragues y sistemas de transmisión completa.',
    icon: 'bi-gear',
  },
  {
    id: 'electronica_control',
    name: 'Electrónica y Sistemas de Control',
    category: 'Reparaciones',
    price: 300.00,
    description: 'Diagnóstico y reparación de sistemas electrónicos, ECU, inyección electrónica y controles digitales.',
    icon: 'bi-cpu',
  },
  {
    id: 'carroceria_personalizacion',
    name: 'Carrocería y Personalización',
    category: 'Reparaciones',
    price: 400.00,
    description: 'Reparación de carrocería, pintura personalizada y modificaciones estéticas a medida.',
    icon: 'bi-palette',
  },
  // Diagnósticos
  {
    id: 'diagnostico_emisiones',
    name: 'Diagnóstico de Emisiones y Rendimiento',
    category: 'Diagnósticos',
    price: 150.00,
    description: 'Análisis de emisiones, consumo de combustible y rendimiento general del motor.',
    icon: 'bi-speedometer2',
  },
  {
    id: 'diagnostico_seguridad',
    name: 'Diagnóstico de Seguridad y Dinámica',
    category: 'Diagnósticos',
    price: 180.00,
    description: 'Evaluación de sistemas de frenos, suspensión, neumáticos y estabilidad dinámica.',
    icon: 'bi-shield-check',
  },
  {
    id: 'diagnostico_electrico',
    name: 'Diagnóstico Eléctrico',
    category: 'Diagnósticos',
    price: 120.00,
    description: 'Comprobación de sistemas eléctricos, batería, alternador y cableado completo.',
    icon: 'bi-lightning-charge',
  },
  {
    id: 'diagnostico_mecanico',
    name: 'Diagnóstico Mecánico',
    category: 'Diagnósticos',
    price: 160.00,
    description: 'Inspección completa de componentes mecánicos, desgastes y ajustes necesarios.',
    icon: 'bi-gear-wide',
  },
  // Instalaciones
  {
    id: 'instalacion_personalizada',
    name: 'Instalación Personalizada',
    category: 'Instalaciones',
    price: 100.00,
    description: 'Instalación de componentes y accesorios específicos según tus necesidades y preferencias.',
    icon: 'bi-wrench',
  },
  {
    id: 'instalaciones_seguridad',
    name: 'Instalaciones de Seguridad',
    category: 'Instalaciones',
    price: 200.00,
    description: 'Montaje de sistemas de seguridad, alarmas, bloqueadores y dispositivos antitheft.',
    icon: 'bi-shield-shaded',
  },
  {
    id: 'instalaciones_rendimiento',
    name: 'Instalaciones de Rendimiento',
    category: 'Instalaciones',
    price: 350.00,
    description: 'Montaje de componentes para mejorar el rendimiento: escapes, filtros, reprogramaciones.',
    icon: 'bi-graph-up',
  },
  {
    id: 'accesorios_personalizados',
    name: 'Accesorios Personalizados',
    category: 'Instalaciones',
    price: 150.00,
    description: 'Instalación de accesorios estéticos y funcionales para personalizar tu motocicleta.',
    icon: 'bi-stars',
  },
];

export const searchSuggestionsData: SearchSuggestion[] = servicesData.map(service => ({
  id: service.id,
  name: service.name,
  category: service.category,
  icon: service.icon,
  price: service.price.toFixed(2),
}));